import type { Transaction } from '../types/transaction';

export const mockTransactions: Transaction[] = [
  {
    _id: '1',
    type: 'expense',
    amount: 450,
    category: 'Food & Dining',
    date: '2026-03-24',
    description: 'Lunch at Saravana Bhavan',
    paymentMethod: 'upi',
    tags: ['food', 'restaurant'],
  },
  {
    _id: '2',
    type: 'income',
    amount: 65000,
    category: 'Salary',
    date: '2026-03-01',
    description: 'March salary credit',
    paymentMethod: 'bank_transfer',
    tags: ['salary'],
  },
  {
    _id: '3',
    type: 'expense',
    amount: 12000,
    category: 'Rent',
    date: '2026-03-05',
    description: 'Monthly house rent',
    paymentMethod: 'bank_transfer',
    tags: ['rent', 'monthly'],
  },
  {
    _id: '4',
    type: 'expense',
    amount: 999,
    category: 'Bills & Utilities',
    date: '2026-03-10',
    description: 'Internet bill - Airtel',
    paymentMethod: 'card',
    tags: ['bill', 'internet'],
  },
  {
    _id: '5',
    type: 'expense',
    amount: 2500,
    category: 'Shopping',
    date: '2026-03-12',
    description: 'T-shirts from Myntra',
    paymentMethod: 'upi',
    tags: ['clothing'],
  },
  {
    _id: '6',
    type: 'income',
    amount: 15000,
    category: 'Freelance',
    date: '2026-03-08',
    description: 'Logo design project',
    paymentMethod: 'bank_transfer',
    tags: ['freelance', 'design'],
  },
  {
    _id: '7',
    type: 'expense',
    amount: 350,
    category: 'Travel',
    date: '2026-03-15',
    description: 'Uber to office',
    paymentMethod: 'upi',
    tags: ['transport'],
  },
  {
    _id: '8',
    type: 'expense',
    amount: 1200,
    category: 'Entertainment',
    date: '2026-03-18',
    description: 'Movie night + snacks',
    paymentMethod: 'card',
    tags: ['movie', 'fun'],
  },
  {
    _id: '9',
    type: 'expense',
    amount: 3200,
    category: 'Groceries',
    date: '2026-03-20',
    description: 'Weekly groceries - BigBasket',
    paymentMethod: 'upi',
    tags: ['groceries', 'weekly'],
  },
  {
    _id: '10',
    type: 'expense',
    amount: 500,
    category: 'Health & Medical',
    date: '2026-03-22',
    description: 'Pharmacy - medicines',
    paymentMethod: 'cash',
    tags: ['health'],
  },
  {
    _id: '11',
    type: 'income',
    amount: 5000,
    category: 'Gifts',
    date: '2026-03-14',
    description: 'Birthday gift from uncle',
    paymentMethod: 'upi',
    tags: ['gift'],
  },
  {
    _id: '12',
    type: 'expense',
    amount: 649,
    category: 'Bills & Utilities',
    date: '2026-03-15',
    description: 'Netflix subscription',
    paymentMethod: 'card',
    tags: ['subscription', 'entertainment'],
  },
];
